"""initial

Revision ID: 160506f8adf9
Revises: 
Create Date: 2025-02-17 21:38:32.595788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '160506f8adf9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_types',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('type_device', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('type_device')
    )
    op.create_table('devices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type_device', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('building', sa.String(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('location_description', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'token'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('tg_id', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('device_admins',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('admin', sa.BigInteger(), nullable=True),
    sa.Column('device', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['admin'], ['users.id'], ),
    sa.ForeignKeyConstraint(['device'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('problem_types',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('type_device', sa.BigInteger(), nullable=True),
    sa.Column('name_problem', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['type_device'], ['device_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('problems',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('type_problem', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('date_updated_status', sa.DateTime(), nullable=True),
    sa.Column('resolver', sa.BigInteger(), nullable=True),
    sa.Column('device', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['device'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['resolver'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('problem_authors',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('author', sa.BigInteger(), nullable=True),
    sa.Column('problem', sa.BigInteger(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['users.id'], ),
    sa.ForeignKeyConstraint(['problem'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problem_authors')
    op.drop_table('problems')
    op.drop_table('problem_types')
    op.drop_table('device_admins')
    op.drop_table('users')
    op.drop_table('tokens')
    op.drop_table('devices')
    op.drop_table('device_types')
    # ### end Alembic commands ###
