"""add tg_chat

Revision ID: 9579f5628372
Revises: 8a5803f7892c
Create Date: 2025-03-11 00:15:24.563482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9579f5628372'
down_revision: Union[str, None] = '8a5803f7892c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'device_admins', ['id'])
    op.create_unique_constraint(None, 'device_types', ['id'])
    op.create_unique_constraint(None, 'devices', ['id'])
    op.create_unique_constraint(None, 'problem_authors', ['id'])
    op.create_unique_constraint(None, 'problem_types', ['id'])
    op.create_unique_constraint(None, 'problems', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'problems', type_='unique')
    op.drop_constraint(None, 'problem_types', type_='unique')
    op.drop_constraint(None, 'problem_authors', type_='unique')
    op.drop_constraint(None, 'devices', type_='unique')
    op.drop_constraint(None, 'device_types', type_='unique')
    op.drop_constraint(None, 'device_admins', type_='unique')
    # ### end Alembic commands ###
