"""add tg code table

Revision ID: d9dcaf4819a2
Revises: a007fbeb63f5
Create Date: 2025-03-28 00:59:28.998340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9dcaf4819a2'
down_revision: Union[str, None] = 'a007fbeb63f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_codes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=True),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tg_id'], ['tg_chats.tg_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.alter_column('tg_chats', 'tg_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_unique_constraint("unique_tg_chats_id", 'tg_chats', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_tg_chats_id", 'tg_chats', type_='unique')
    op.alter_column('tg_chats', 'tg_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_table('tg_codes')
    # ### end Alembic commands ###
